# OrderPortal: Settings file.

# This file changes the default values set in the 'settings' dictionary
# defined in the '__init__.py' file.

### You should copy this file and modify for your site.
### Name the file 'hostname.yaml', where hostname is the
### obtained by the following shell command:
### $ python -c "import socket; print socket.gethostname().split('.')[0]"

### In particular, 'your-domain.com' must be changed.

# Official URL to the portal; access from the outside world.
#BASE_URL: 'http://my-domain.com/'
BASE_URL: 'http://localhost:8886/'

# tornado server port; may be different from above if proxy is used.
PORT: 8886

# CouchDB server
# DB_SERVER: 'http://username:password@localhost:5984/'
DB_SERVER: 'http://localhost:5984/'
DATABASE: 'orderportal'

# Logging and debug.
TORNADO_DEBUG: true
LOGGING_DEBUG: true

# Login
COOKIE_SECRET: 'a long string of random characters %!120()='
PASSWORD_SALT: 'a long string of random characters ?=}%&;19'

# Site customization; change for your site
SITE_DIR:  '{ROOT_DIR}/site'
SITE_NAME: 'My Order Portal'
SITE_SUPPORT_EMAIL: 'my.email@my-domain.com'

# The icon files must be in the SITE_DIR; absolute file path is not allowed.
SITE_FAVICON:     'orderportal32.png'
SITE_NAVBAR_ICON: 'orderportal32.png'
SITE_HOME_ICON:   'orderportal144.png'

# Account messages definitions
ACCOUNT_MESSAGES_FILEPATH: '{SITE_DIR}/account_messages.yaml'

# Order status and transition definition files
ORDER_STATUSES_FILEPATH:    '{SITE_DIR}/order_statuses.yaml'
ORDER_TRANSITIONS_FILEPATH: '{SITE_DIR}/order_transitions.yaml'
ORDER_MESSAGES_FILEPATH:    '{SITE_DIR}/order_messages.yaml'

# Use sequentially numbered order identifiers
ORDER_IDENTIFIER_FORMAT: 'MY{0:=05d}'
ORDER_IDENTIFIER_REGEXP: 'MY\d+'

# The statuses to show in the orders list.
# The statuses must be defined in the ORDER_STATUSES_FILEPATH file.
ORDERS_LIST_STATUSES:
  - submitted
  - accepted
  - processing
  - closed

# University symbols (abbreviations), names and rank in list.
# Optional, may be set to null.
UNIVERSITIES_FILEPATH: '{SITE_DIR}/swedish_universities.yaml'

# Country names and codes. Optional, may be set to null.
COUNTRY_CODES_FILEPATH: '{SITE_DIR}/country_codes.yaml'

# Subject codes, terms in a hierarchy. Optional, may be set to null.
SUBJECT_TERMS_FILEPATH: '{SITE_DIR}/subject_terms.yaml'

# Messages; email server info.
MESSAGE_SENDER_EMAIL: '"OrderPortal Support" <support@my-domain.com>'
EMAIL:
  HOST: 'localhost'
